### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by klikr** [netresearch/jira-export#3]
Hi,

thank you so much for this piece of software. Could you please provide an option to include attachments? Like that, it would be a perfect archiving solution! :)

Thanks in advance,
Peter.

**Comment by chrismoeller** [comment]
Hi Peter, 
you closed this as complete (two years ago). I just test-ran the tool and could not find any way to get the attachments, and there's no reference to this feature in the code. Am I missing sth.? Thanks for clarifiying and have a fine day!
Chris

**Comment by klikr** [comment]
Hi Chris,
I maybe should have closed this with a different resolution, as I was in the end unable to export attachments along with the issues. I did close it because there was no reaction.

**Comment by pekohub** [comment]
...
